#server.port=4005
spring.application.name=auth-service

# JSON Support
spring.http.converters.preferred-json-mapper=jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/insurance_db
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DATABASE_URL}
# JWT Secret
jwt.secret=c3VwZXJTZWNyZXRLZXlGb3JKV1RDb25maWd1cmF0aW9uMTIz

# Logging
logging.level.com.ain.authservice=DEBUG
server.port=${PORT:4005}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gigigigi0987654@gmail.com
spring.mail.password=deaz quee lqzi srtt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

