### create a new client entity POST
#locally
#POST http://localhost:4000/clients

#api-gateway
POST http://localhost:4004/api/clients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "fullName": "Johujynn Doeee",
  "dateOfBirth": "2001-11-10",
  "passportNumber": "AN4884564",
  "pin": "25544568158797",
  "address": "Bishkek",
  "phoneNumber": "+996775862198"

}

###