### create a new client entity POST
POST http://localhost:4000/clients
Content-Type: application/json

{
  "fullName": "J k D",
  "dateOfBirth": "2003-01-20",
  "passportNumber": "AN6554564",
  "pin": "22505198520004",
  "address": "Bishkek",
  "phoneNumber": "+996552555565"

}

###