### Update an existing client entity
PUT http://localhost:4000/clients/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
  "fullName": "John Doe Kim",
  "dateOfBirth": "2003-01-20",
  "passportNumber": "AN 6554564",
  "pin": "22505198520074",
  "address": "Bishkek",
  "phoneNumber": "+996552555565"

}
###