server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-login
          uri: http://auth-service:4005
          predicates:
            - Path=/login
        - id: auth-service-validate
          uri: http://auth-service:4005
          predicates:
            - Path=/validate
        - id: auth-service-register
          uri: http://auth-service:4005
          predicates:
            - Path=/register
        - id: auth-service-forgot-password
          uri: http://auth-service:4005
          predicates:
            - Path=/forgot-password
        - id: auth-service-reset-password
          uri: http://auth-service:4005
          predicates:
            - Path=/reset-password
        - id: insurance-service-clients
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
        - id: insurance-service-cars
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/cars/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
        - id: insurance-service-drivers
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/drivers/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
        - id: insurance-service-policies
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/policies/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
        - id: insurance-service-policy-download
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/policies/*/download
          filters:
            - StripPrefix=1
            - name: JwtValidation
        - id: insurance-service-chat
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
        - id: insurance-service-chat-ws
          uri: http://insurance-service:4000
          predicates:
            - Path=/ws-chat/**
          filters:
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.ain.apigateway: INFO