###  create a new driver entity POST
POST http://localhost:4000/drivers
Content-Type: application/json

{ "policy": {
  "policyNumber": "0505060"
},
  "fullName": "Kim Diana Lee",
  "birthDate": "2000-10-25",
  "licenseNumber": "BG 54867951",
  "drivingExperience": "2000-01-01"
}

###