###  update an existing driver entity
PUT http://localhost:4000/drivers/770e8400-e29b-41d4-a716-446655440001
Content-Type: application/json

{ "policy": {
  "policyNumber": "0505060"
},
  "fullName": "Петрова Мария Ивановна",
  "birthDate": "1990-08-20",
  "licenseNumber": "OG 6543217",
  "drivingExperience": "2019-08-20"
}

###