### Delete an entity
#locally
#DELETE http://localhost:4000/cars/0285849e-55c0-49b3-83ba-213c386cc732

#api-gateway
DELETE http://localhost:4004/api/cars/0285849e-55c0-49b3-83ba-213c386cc732
Authorization: Bearer {{token}}
###