### update an existing car entity
#locally
#PUT http://localhost:4000/cars/0285849e-55c0-49b3-83ba-213c386cc732

#api-gateway
PUT http://localhost:4004/api/cars/0285849e-55c0-49b3-83ba-213c386cc732
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "brand": "Zeekr",
  "model": "2052",
  "manufactureYear": "2015",
  "vin": "JTDKB20U3035846941",
  "licensePlate": "08KG098AC",
  "registrationAuthority": "411011",
  "registrationDate": "2025-01-06",
  "techPassportNumber": "AB 096203",
  "engineVolume": null,
  "maxAllowedWeight": null,
  "batteryCapacity": "156.0",
  "passengerCapacity": null,
  "vehicleType": "ELECTRIC_CAR",
  "owner": {
    "id": "550e8400-e29b-41d4-a716-446655440002",
    "fullName": "Сидоров Алексей Викторович",
    "dateOfBirth": "1978-11-25",
    "phoneNumber": "+996555112233",
    "passport_number": "AN1122334",
    "pin": "10211198233445",
    "address": "г. Ош, ул. Ленина 67"
  }
}
###